apiVersion: 1

datasources:
  - name: InfluxDB_v2_Flux
    type: influxdb
    access: proxy
    url: http://{{ host }}:8086
    uid: x_9-kjU4k
    jsonData:
      version: Flux
      organization: {{ influxdb_org }}
      defaultBucket: {{ influxdb_bucket }}
      tlsSkipVerify: true
    secureJsonData:
      token: {{ influxdb_token }}